### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by ajtga** [ajtga/Calculator#23]
We need to agree with where to deal with the user input (in the operation function or in the menu), I think the first option is a better solution, what do you think?

**Comment by cfsouza** [comment]
Perhaps, we should define how the calculator should look alike first (if not defined yet). I think a regular scientific calculator would be a good first trial. Hence, we would insert the first factor and then, after, the operation/function. If it is an arithmetic operation, we then would need to insert the last factor to evaluate the expression. Does that help any?

**Comment by ewerton94** [comment]
I've followed the idea that @cfsouza sad and applied. I don't know if this is the better way to do, but it works.
